# Why do I need to separate parts of my README and compile
# them together?
#
# Some components of my README are used elsewhere.
name: Compile README Sources

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  compile_readme:
    name: 'Compile README'

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: compile
      run: | # Place files in order here.
        cat README.md whativebeenupto.md > README.md

    - name: commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "compile README.md"
        git push origin HEAD:main
